spring:
  data:
    mongodb:
      database: library
      port: 27017
      host: localhost

mongock:
#  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.library.mongock.changelog

logging:
  level:
    root: DEBUG