spring:
  logging:
    level:
      ROOT: debug

  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false

  data:
    mongodb:
      database: libraryTransfer
      port: 27017
      host: localhost

  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true

  shell:
    interactive:
      enabled: true

  sql:
    init:
      mode: always

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true